on:
  push:
    branches: [master, ubuntu_25.10]
    paths: ['**/*.sh']
  pull_request:
    branches: [master, ubuntu_25.10]
    paths: ['**/*.sh']

jobs:
  conditional-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # Figure out if any .sh files were *modified*
      - name: Detect modified *.sh files
        id: check_mods
        run: |
          echo "MODIFIED=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.sh$' | grep -v '^#' | wc -l)" >> $GITHUB_ENV

      # Skip the rest if no .sh files were modified
      - name: Skip if nothing changed
        if: ${{ env.MODIFIED == '0' }}
        run: echo "No Bash scripts were modified – skipping job."

      # Continue with your actual job only when MODIFIED > 0
      - name: Run Bash lint
        if: ${{ env.MODIFIED != '0' }}
        run: shellcheck **/*.sh
